services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  processor:
    build: ./processor
    depends_on:
      - spark-master
      - spark-worker
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPARK_HOST=spark-master
      - SPARK_PORT=7077
    ports:
      - "8000:8000"